version: "3.9"

services:
  reverse-proxy:
    image: caddy:2
    env_file: ./config/.env
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
      - ./data/basemaps:/srv/basemaps:ro
    depends_on:
      - api
      - object-store
      - tiler
    restart: unless-stopped
    profiles: ["core"]

  object-store:
    image: minio/minio:latest
    command: server /data --console-address ":${MINIO_CONSOLE_PORT:-9090}"
    env_file: ./config/.env
    environment:
      MINIO_VOLUMES: /data
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9090:9090"
    restart: unless-stopped
    profiles: ["core"]

  object-store-init:
    image: minio/mc:latest
    env_file: ./config/.env
    depends_on:
      - object-store
    entrypoint: ["/bin/sh","-c"]
    command: >-
      set -e;
      until /usr/bin/mc alias set local ${MINIO_ENDPOINT:-http://object-store:9000} ${MINIO_ROOT_USER:-localminio} ${MINIO_ROOT_PASSWORD:-change-me-now}; do echo 'Waiting for MinIO...'; sleep 2; done;
      /usr/bin/mc mb -p local/${S3_BUCKET_RAW:-raw} || true;
      /usr/bin/mc mb -p local/${S3_BUCKET_DERIVED:-derived} || true;
      /usr/bin/mc mb -p local/${S3_BUCKET_TILES:-tiles} || true;
      /usr/bin/mc mb -p local/${S3_BUCKET_LOGS:-logs} || true;
      echo 'MinIO buckets ensured.'
    restart: "on-failure"
    profiles: ["core"]

  postgres:
    image: postgis/postgis:15-3.4
    env_file: ./config/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    profiles: ["core"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-osm} -d ${POSTGRES_DB:-osm} -h 127.0.0.1 -p ${POSTGRES_PORT:-5432}"]
      interval: 5s
      timeout: 5s
      retries: 10

  ingestion:
    build: ./services/ingestion
    env_file: ./config/.env
    volumes:
      - ./services/ingestion/src:/app/src
      - ./data/raw:/data/raw
    depends_on:
      - object-store
    restart: unless-stopped
    profiles: ["ingestion"]

  basemap:
    build: ./services/basemap
    env_file: ./config/.env
    volumes:
      - ./services/basemap/src:/app/src
      - ./data/basemaps:/data/basemaps
    depends_on:
      - postgres
    ports:
      - "8082:8080"
    restart: unless-stopped

  api:
    build: ./services/api
    env_file: ./config/.env
    depends_on:
      object-store:
        condition: service_started
      postgres:
        condition: service_healthy
    ports:
      - "8081:8081"
    restart: unless-stopped
    profiles: ["core"]

  tiler:
    build: ../services/tiler
    env_file: ./config/.env
    depends_on:
      - object-store
    ports:
      - "8083:8083"
    restart: unless-stopped
    profiles: ["core"]

  frontend:
    build: ./services/frontend
    env_file: ./config/.env
    depends_on:
      - api
    ports:
      - "4173:4173"
    restart: unless-stopped

  monitoring:
    build: ./services/monitoring
    env_file: ./config/.env
    profiles: ["monitoring"]
    restart: unless-stopped

volumes:
  caddy_data:
  caddy_config:
  minio_data:
  postgres_data:
