version: '3.8'

services:
  postgres:
    image: postgis/postgis:15-3.3
    container_name: atmos-postgres-dev
    environment:
      POSTGRES_DB: osm
      POSTGRES_USER: osm
      POSTGRES_PASSWORD: osmpassword
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    command: postgres -c max_connections=200

  renderer:
    build:
      context: .
      dockerfile: services/cyclosm/renderer/Dockerfile
    container_name: atmos-renderer-dev
    ports:
      - "8080:8080"
    environment:
      PGHOST: postgres
      PGDATABASE: osm
      PGUSER: osm
      PGPASSWORD: osmpassword
      PGPORT: 5432
      CYCLOSM_PROJECT_MML: ./CyclOSM-CSS-Master/project.mml
      PORT: 8080
      METATILE: 1
    volumes:
      - ./CyclOSM-CSS-Master:/app/CyclOSM-CSS-Master
      - ./services/cyclosm/renderer:/app/services/cyclosm/renderer
      - ./fonts:/usr/share/fonts/custom
    depends_on:
      - postgres

  importer:
    build:
      context: .
      dockerfile: services/cyclosm/importer/Dockerfile
    container_name: atmos-importer-dev
    environment:
      PGHOST: postgres
      PGDATABASE: osm
      PGUSER: osm
      PGPASSWORD: osmpassword
      PGPORT: 5432
    volumes:
      - ./data:/app/data
      - ./CyclOSM-CSS-Master:/app/CyclOSM-CSS-Master
    depends_on:
      - postgres
    profiles:
      - import

volumes:
  postgres_data: